apiVersion: app.example.org/v1beta1
kind: AppService
metadata:
  name: appservice
spec:
  # TODO(user): Add fields here
  size: 1
  image: nginx:1.16.1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002